---
- name: Install and Configure Grafana
  hosts: all
  become: true
  tasks:
    - name: Install gpg
      apt:
        name: gnupg,software-properties-common
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Add grafana gpg key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        validate_certs: no

    - name: Add grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        validate_certs: no

    - name: Install grafana
      apt:
        name: grafana
        state: latest
        update_cache: yes
        cache_valid_time: 3600

    - name: Start service grafana-server
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Wait for service up
      uri:
        url: "http://127.0.0.1:3000"
        status_code: 200
      register: __result
      until: __result.status == 200
      retries: 120
      delay: 1