Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"

    # Enable Ansible provisioning
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yaml"
    end
  end
