apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: demo-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: zerodha-demo-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          hostPort: 8080
        env:
        - name: DEMO_APP_ADDR
          value: ":8080"
        - name: DEMO_REDIS_ADDR
          value: "redis-service:6379"
        livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: demo-ops
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
