apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: demo-ops
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{path}}/nginx-conf"


# Create resource using the below command
# cat nginx-pv.yaml | sed s+{{path}}+$(pwd)+g | kubectl apply -f -