apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-app-resource-quota
  namespace: demo-ops
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
